### ISSUE TITLE
I am getting multiple view missing error, any solutions?

### ISSUE THREAD

**Issue by ohid** [LMS-Laravel/OLD-LMS-Laravel#10]
now I'm getting this error. What is the solution please?
Anyway a good work.

ErrorException in compiled.php line 13913:
View [Default.views.layouts.breadcrumbs] not found. (View: D:\Projects\xampp2\htdocs\laravel\Laravel_lms\Themes\Default\views\dashboard\learning.blade.php)

Thanks

**Comment by angelmartz** [comment]
I get same error

View [Default.views.errors.form-error] not found. (View: C:\wamp\www\lmslaravel\Themes\Default\views\auth\login.blade.php)

**Comment by angelkurten** [comment]
I'll try in Windows and see what happens

**Comment by ayndev** [comment]
For me the solution was to remove the view_path() methods from all the @include and @extend
and for the breadcrumbs is to change its config file to :
'view' => 'layouts.breadcrumbs' 

I'm using Mac
