### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by ITwrx** [LMS-Laravel/OLD-LMS-Laravel#11]
when running `php artisan app:install` i get 

``` [Illuminate\Database\QueryException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tables_in_LMS' in 'where clause' (SQL: SHOW TABLES WHERE Tables_in_LMS-laravel NOT REGEXP "[[.low-line.]]")

```

**Comment by angelkurten** [comment]
Which operating system to use?

**Comment by ITwrx** [comment]
archlinux(mariadb 10.1.13-1, nginx 1.8.1-3, php 7.0.5-1)
thanks

**Comment by vrtc** [comment]
hi, me with the same problem itself: archlinux + mariadb + apache2 + php 5.5.9

**Comment by dmitriy-01** [comment]
I had the same issue - it was because of the dash in DB name that I used - "lms-laravel".

The fix is to put back-ticks in SQL query around `'.$name.'` in Modules/User/Database/Seeders/UserTableSeeder.php, line 134:

`$data = DB::select('SHOW TABLES WHERE `'.$name.'` NOT REGEXP "[[.low-line.]]"');`

After this `php artisan app:install` works fine.

**Comment by angelkurten** [comment]
Hi, install success in Ubuntu, not have archlinux

**Comment by ITwrx** [comment]
@websquared thanks for the info. will check it out when i get a chance.

@angelkurten thanks for the info. Is this package compat with laravel 5.2x? the readme doesn't mention any compatability info except "laravel 5". Please consider adding your tested config(incl versions). 

IMHO, projects should consider development and testing with a distro that is closer to upstream in it's release cycle. For example, arch, gentoo, lfs, or similar.  Choosing a distro with a much slower release cycle as reference distro means people using current, stable gnu+linux are expected to either change distros or "go back in time" by many releases/years(?) to reach parity with distros with slower release cycles. Neither of which is reasonable. Nothing against those distros, but catering to their chosen cycle instead of upstream is backwards. 

thanks

**Comment by vrtc** [comment]
@angelkurten 
the thing MariaDB versions. archlinux here is not to blame

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
