### ISSUE TITLE
Install issue:Posix collating

### ISSUE THREAD

**Issue by pisyek** [LMS-Laravel/OLD-LMS-Laravel#12]
When i app:install i got an error as follows:
![capture](https://cloud.githubusercontent.com/assets/10695986/14582230/c8cd47b4-0431-11e6-8e64-6d848b2d5c10.PNG)

Appreciate if you could advice.

**Comment by angelkurten** [comment]
Hi, install success in Ubuntu

**Comment by jestonihpi** [comment]
is there a turn around fix for windows?

**Comment by jestonihpi** [comment]
i manage to run the app:install command by updating ;
modules/User/Database/Seeders/UserTableSeeder.php

line 134: function permissionsAllSeeder()

to  $data = DB::select('SHOW TABLES from '.env('DB_DATABASE', 'forge') );

**Comment by fahreza007** [comment]
Thank you save my live

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
