### ISSUE TITLE
How Can I Access The Dashboard?

### ISSUE THREAD

**Issue by Ivannnnn** [LMS-Laravel/OLD-LMS-Laravel#13]
At which url do I access the dashboard? "Admin" or "dashboard" don't do it.

**Comment by akitengineer** [comment]
Goto: {base_url}/auth/login and use following credentials 

User: admin

Pass: admin123

**Comment by jeffcore** [comment]
The credentials worked for my first login. Then gave me this error: 

Whoops! Error

El usuario o la contraseña no son correctos

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
