### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by walkwelsubmission** [LMS-Laravel/OLD-LMS-Laravel#14]
Nothing works except login and rest everything is empty links. Can you please update here the working one.

**Comment by akitengineer** [comment]
It is under development so some links may not work.

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
