### ISSUE TITLE
I can able to install the app. I cannot able to view dashboard or admin panel once the installation done. please share the url for this.

### ISSUE THREAD

**Issue by dhascruz** [LMS-Laravel/OLD-LMS-Laravel#15]

**Comment by akitengineer** [comment]
Click on platform or goto {base_url}/auth/login then login using following credentials

User: admin
Pass: admin123

**Comment by dhascruz** [comment]
http://localhost:8000/auth/login not able

ErrorException in FileViewFinder.php line 137: View [Default.views.errors.form-error] not found. (View: E:\Bitnami\meanstack-3.2.8-2\apache2\htdocs\lms-laravel\Themes\Default\views\auth\login.blade.php)

I am receiving this error. please help me.

I am also interested to contribute in the lms. I am having good knowledge LMS and Moodle.

**Comment by akitengineer** [comment]
Make sure you updated your composer dependencies correctly.

**Comment by fahreza007** [comment]
I Update my composer and success but not fix this problem

**Comment by ak-floweraura** [comment]
Hi @fahreza007 

This project is not updated so far, I would suggest another project of laravel for LMS:

https://github.com/LaravelDaily/QuickLMS

Git this a try, it also has a nice introductory videos on youtube.

**Comment by fahreza007** [comment]
@ak-floweraura 
Ok Thank you

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
