### ISSUE TITLE
InvalidArgumentException in Finder.php line 546

### ISSUE THREAD

**Issue by serdarkok** [LMS-Laravel/OLD-LMS-Laravel#16]
Hi There;
I get that error message:
The "/media/disk/disk2/http/loopl/project/public/photos/1" directory does not exist. 

1 is user id. you know.

If i create folder (user id = 1) than fix this. How can i auto create user id folder on photos directory? 
How can i fix this?

my lfm.php : 
    *...
    'use_package_routes'    => true,
    'middlewares'           => ['web','auth'],
    'prefix'           => 'laravel-filemanager',
    'allow_multi_user'      => true,
    'user_field'            => 'id',
    *...

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
