### ISSUE TITLE
ErrorException in FileViewFinder.php line 137

### ISSUE THREAD

**Issue by Bkoech** [LMS-Laravel/OLD-LMS-Laravel#17]
I get this error when i access the login page what could be the problem

ErrorException in FileViewFinder.php line 137: View [Default.views.errors.form-error] not found. (View: C:\wamp64\www\alms\Themes\Default\views\auth\login.blade.php)

**Comment by punit-gajjar** [comment]
Same problem...

**Comment by elib0** [comment]
any solution ?

**Comment by ATNoosh** [comment]
Same problem. any solution?

**Comment by VedanshGoyal** [comment]
Any Fix for that ???

**Comment by fahreza007** [comment]
Same proble, How to fix this problem?

**Comment by fahreza007** [comment]
Changing @include(view_path('errors.form-error')) to @include('errors.form-error') in Themes\Default\views\auth\login.blade.php fixed this issue for me 
@websquared

**Comment by PSalador** [comment]
Changing @extends(view_path('layouts.base_auth')) to @extends('layouts.base_auth') in Themes\Default\views\auth\login.blade.php

**Comment by jeremykenedy** [comment]
I have corrected this in PR https://github.com/LMS-Laravel/LMS-Laravel/pull/25

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
