### ISSUE TITLE
Error in Database Migration

### ISSUE THREAD

**Issue by msauditech** [LMS-Laravel/OLD-LMS-Laravel#20]
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'POSIX co
llating elements are not supported at offset 1' from regexp (SQL: SHOW TABL
ES WHERE Tables_in_laralms NOT REGEXP "[[.low-line.]]")

**Comment by msaudicse** [comment]
Fixed it by changing [[.low-line].]"

        $data = DB::select('SHOW TABLES WHERE '.$name.' NOT REGEXP "[\.low-line\.]"');

**Comment by msauditech** [comment]
In my case (windows 7 + xampp) 
I changed  line 134 file Modules\Users\database\Seederrs\UserTableSeeder.php to
  $data = DB::select('SHOW TABLES WHERE Tables_in_laralms NOT like "%low-line%"');

and it worked.

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
