### ISSUE TITLE
    Failed to download pingpong/themes from dist: The "https://api.github.com/repos/pingpong-labs/themes/zipball/6953a97b8b8c4ca5b82bae04de1c689199540e26"

### ISSUE THREAD

**Issue by rajanmodi30** [LMS-Laravel/OLD-LMS-Laravel#21]
[RuntimeException]                                                           
  Failed to clone https://github.com/pingpong-labs/themes.git via https, ssh   
  protocols, aborting.                                                         
  - https://github.com/pingpong-labs/themes.git                                
    Cloning into '/var/www/html/LMS-Laravel-master/studity/vendor/pingpong/th  
  emes'...                                                                     
    fatal: unable to access 'https://github.com/pingpong-labs/themes.git/': C  
  ould not resolve host: github.com                                            
  - git@github.com:pingpong-labs/themes.git                                    
    Cloning into '/var/www/html/LMS-Laravel-master/studity/vendor/pingpong/th  
  emes'...                                                                     
    ssh: Could not resolve hostname github.com: Name or service not known      
    fatal: Could not read from remote repository.                              
                                                                               
    Please make sure you have the correct access rights                        
    and the repository exists.

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
