### ISSUE TITLE
I getting this error, if the table doesn't exist how to define  the table structure

### ISSUE THREAD

**Issue by mommand** [LMS-Laravel/OLD-LMS-Laravel#22]
![screen shot 2017-07-26 at 11 44 42 pm](https://user-images.githubusercontent.com/4653953/28639195-974ddd9e-725c-11e7-8d3a-0d25f083d895.png)

**Comment by laravellously** [comment]
You have not run DashboardSeeder. To do this,
1. Run in your terminal: $ php artisan app:install
OR you can manually run the migration and seeder: $ php artisan module:migrate, then you run $ php artisan module:seed

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
