### ISSUE TITLE
ErrorException in Collection.php line 1043: Undefined offset: 0

### ISSUE THREAD

**Issue by rokethom** [LMS-Laravel/OLD-LMS-Laravel#24]
![screenshot_1](https://user-images.githubusercontent.com/24378849/31302030-b8cdb9f8-ab28-11e7-9b20-425da8dd26e2.png)

**Comment by laravellously** [comment]
I encountered this issue too after installation. It is as a result of incomplete installation. I overcame it by doing the following:
1. Goto UserTableSeeder in App/Modules/User/Database/Seeders
2. Comment this line "$this->permissionsAllSeeder();" (line19) under public function run()
3. Drop the database
4. Run in your terminal $php artisan app:install

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
