### ISSUE TITLE
Views missing

### ISSUE THREAD

**Issue by aarontanzk** [LMS-Laravel/OLD-LMS-Laravel#26]
Hi I did a git clone then composer install but there are no views included in the project.

Anyone knows whats the problem?

**Comment by jeremykenedy** [comment]
Did you run step 4 outlined in the readme? 

`php artisan app:install`

**Comment by aarontanzk** [comment]
oh yeah it works now.

Another problem: any idea how to disable mailgun? I dont have my domain yet so its a problem

**Comment by jeremykenedy** [comment]
So this is no longer an open issue?

**Comment by kamaroly** [comment]
No it's still there, unable to see admin views

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
