### ISSUE TITLE
php artisan app:install not working 

### ISSUE THREAD

**Issue by coZet** [LMS-Laravel/OLD-LMS-Laravel#29]
I don't found any of module , themes such folders., 
First time i was install and run it's ok, when i clear browser that's got route error.
so i re-clone from git and new installation at php artisan app:install not working.

**Comment by micahaza** [comment]
Same issue here.

**Comment by vwaaala** [comment]
app:install command not found :(

**Comment by Rattone** [comment]
...this new repo is a simple installation of laravel 5.5 without anything else 👎

**Comment by jwjcmw** [comment]
if you clone the repo and then 
```git checkout dev```
I think it gets you back to the last version before it was rebased to the empty 5.5 install.  The install runs for me now, but there are still errors.

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
