### ISSUE TITLE
Vendor Folder Missing

### ISSUE THREAD

**Issue by carmelodiventi** [LMS-Laravel/OLD-LMS-Laravel#30]
when launch the command  "php artisan app:install" there are some errors 

Failed opening required '/Applications/MAMP/htdocs/LMS-Laravel/vendor/autoload.php' (include_path='.:/usr/local/php5/lib/php') in /Applications/MAMP/htdocs/LMS-Laravel/artisan on line 18

i check but the vendor is missing in folder project

Thanks

**Comment by angelmartz** [comment]
You should run first

composer install

**Comment by carmelodiventi** [comment]
ah, thanks you

Cordiali saluti
*Carmelo Di Venti*
Progettazione e Realizzazione siti web
*mobile: *+39 331.3567032
*site:* carmelodiventi.com <http://www.carmelodiventi.com>
*e-mail*: hello@carmelodiventi.com

2018-02-14 17:34 GMT+00:00 Angel Martz <notifications@github.com>:

**Comment by Rattone** [comment]
I think it is necessary to write it in the installation guide... for newbie like me

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
