### ISSUE TITLE
Command aap:install is not defined!!

### ISSUE THREAD

**Issue by yash-6795** [LMS-Laravel/OLD-LMS-Laravel#32]
I ran composer install followed by php artisan app: install, I got below-mentioned errors.

'''Command "app:install" is not defined.  
    Did you mean one of these?             
      app:name                           
      migrate:install '''

**Comment by ghost** [comment]
same as me, i got message

**Command "app:install" is not defined.
Did you mean one of these?
app:name
migrate:install**

**Comment by valonsoft** [comment]
Same issue here. Any fix for this?

**Comment by fenix011** [comment]
Same issue here :-)

**Comment by angelkurten** [comment]
The project will restart soon we hope to have your support you can participate with your ideas in trello and slack 

Trello -> [https://trello.com/b/dv9fqFK2/lms-laravel](https://trello.com/b/dv9fqFK2/lms-laravell)

Slack -> [https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI](https://join.slack.com/t/lmslaravel/shared_invite/enQtMzkzNTUxNzAzMTEwLTVkNDBmZmU1YjEzMWIxNTk5Y2FiOGYyODYxNmFhYjgwYzQ5MjRhOWViOTRkZWM3ZjczOTcxMzVlOTU5YzdiNGI)
