### ISSUE TITLE
empty app/Http/routes.php file

### ISSUE THREAD

**Issue by gavinengel** [LMS-Laravel/OLD-LMS-Laravel#4]
After the composer install command, the new project is missing routes.  Do you recommend some common routes in routes.php?  Perhaps this could contain some example routes, so that the new project has something to display as a 'hello world'?

**Comment by angelkurten** [comment]
Excute the command php artisan app:install for install lms

**Comment by angelkurten** [comment]
The routes are managed directly from each module

**Comment by gavinengel** [comment]
So Apache/Nginx should not point to the public folder of  the NewProject/public/?  I see

**Comment by angelkurten** [comment]
If you must point to the public folder (NewProject / public /), it's just that LMS-laravel is a modular application, and each module sets its own routes, for more information visit https://sky.pingpong-labs.com/docs/2.1/modules, but the rest is all the same.

I'm sorry for my English.

---

Si debe apuntar a la carpeta pública(NewProject/public/), es solo que LMS-Laravel es una aplicacion modular, y cada modulo establece sus propias rutas, para mas informacion visita https://sky.pingpong-labs.com/docs/2.1/modules, pero el resto es todo igual

Lo siento por mi ingles

**Comment by ahmedelhadi** [comment]
Whoops, looks like something went wrong.
2/2 ErrorException in FileViewFinder.php line 137: View [default.views.errors.form_error] not found. (View: /home/vagrant/Code/acad/themes/Default/views/auth/login.blade.php) 

what's problem ?

**Comment by angelkurten** [comment]
It seems that is not the view, see if there is vistam and tell me if the problem continues
