### ISSUE TITLE
Fail on install

### ISSUE THREAD

**Issue by limatheus** [LMS-Laravel/OLD-LMS-Laravel#5]
Hi, 
First I need say thank you for make this awesome app.
I'm got some troubles when I run `**php artisan app:install**`,  starts fine.. 
But when the installer will migrate and seed the modules nothing happens.

I  executed the command `php artisan module:list` and returns empyt.

 See the screenshot 

![screenshot](http://goo.gl/ls7DPI)

Can you help me?

**Comment by angelkurten** [comment]
Hi, 

@limatheus The installation appears to run correctly, just not the command returns details of the execution, check the database or browser.

I'm sorry for my English

---

La instalación parece ejecutarse de forma correcta, solo que el comando aún no retorna detalles de la ejecución, revise la base de datos o en el navegador.

Lo siento por mi ingles

**Comment by limatheus** [comment]
@angelkurten Yo también lo siento por mi ingles,  yo soy brasileño haha
Pero no mi español es peor XD

After I execute the command app:install, when I go to the database manager I got only 4 tables.

And in the browser I access the app at http://localhost:8000, I got a route error

See that were tables migrated

![tables](http://goo.gl/2Zusmm)

**Comment by angelkurten** [comment]
@limatheus 

I went to install the app on my PC and it worked, you are downloading from composer using create-project?

---

Volví a instalar la app en mi PC y todo funcionó perfectamente, ¿estas descargando desde composer utilizando create-project?

![install](http://i.imgur.com/Y8OR8rt.png)

**Comment by limatheus** [comment]
Humm

Maybe a case sensitive problem, I'm running on Linux.

I see two folders for modules **modules** and **Modules**.

Checking now...

**Comment by angelkurten** [comment]
it's possible, Although I work with Homestead which it is based on Ubuntu
