### ISSUE TITLE
ErrorException in D:\LMS\Laravel\vendor\laravel\framework\src\Illuminate\Support\Collection.php line 1045

### ISSUE THREAD

**Issue by corientdev** [LMS-Laravel/OLD-LMS-Laravel#7]
Hi,

 I successfully installed it.

Got only this warning while installing

`Executing Seed for module User
Class [Modules\User\Database\Seeders\UserTableSeeder] does not exists.
Executing Seed for module Dashboard
Class [Modules\Dashboard\Database\Seeders\DashboardTableSeeder] does not exists

Executing Seed for module Course
Class [Modules\Course\Database\Seeders\CourseTableSeeder] does not exists.`

Please suggest what shall i do?

Suggestion : Please host demo somewhere.

**Comment by angelkurten** [comment]
Hi,

Try run: composer dump-autoload

We do not have resources to maintain a host for demo, sorry :(

**Comment by corientdev** [comment]
it didn't helped

**Comment by angelkurten** [comment]
I don't understand

**Comment by angelkurten** [comment]
Verify if modules install in modules folder

**Comment by corientdev** [comment]
Yes everything is installed without fail

can you please upload source code you have as a whole zip with all components not just like composer dependent zip

n Database backup too offcourse

![2016-01-07 22_01_43-mozilla firefox](https://cloud.githubusercontent.com/assets/9655234/12175821/4f14f106-b58a-11e5-92d8-fb82410c052b.png)

**Comment by angelkurten** [comment]
The problem is that the database is still empty, please run php artisan app:install

**Comment by corientdev** [comment]
It is also done

`D:\LMS\laravel>php artisan app:install
Generate Key
Application key [KE0240rpzM63RJPaxOHbH5NIUWZGgxzn] set successfully.
Migrations Basics
Nothing to migrate.
Executing Seeders
Seeded: CountriesSeeder
Seeded Countries
Executing Migrations Modules
Running for module: user
Nothing to migrate.
Running for module: dashboard
Nothing to migrate.
Running for module: course
Nothing to migrate.
Executing Seeders Modules
Executing Seed for module User
Class [Modules\User\Database\Seeders\UserTableSeeder] does not exists.
Executing Seed for module Dashboard
Class [Modules\Dashboard\Database\Seeders\DashboardTableSeeder] does not exists.

Executing Seed for module Course
Class [Modules\Course\Database\Seeders\CourseTableSeeder] does not exists.
Activate theme: Default
Publish assets themes
Asset published from: default`

**Comment by angelkurten** [comment]
One moment please

**Comment by angelkurten** [comment]
Please run composer update and php artisan app:install

**Comment by corientdev** [comment]
Its working.

new error on login page.

and its not in english? :o

![2016-01-08 14_58_54-mozilla firefox](https://cloud.githubusercontent.com/assets/9655234/12194784/6f22abe4-b618-11e5-8751-06fdea8f80c3.png)

**Comment by corientdev** [comment]
To many bugs bro please tag it as alpha version

**Comment by angelkurten** [comment]
Alpha tagged , sorry for errors, this in developed

Thanks for issues
