### ISSUE TITLE
default.views.errors.form_error

### ISSUE THREAD

**Issue by ahmedelhadi** [LMS-Laravel/OLD-LMS-Laravel#9]
Whoops, looks like something went wrong.
2/2 ErrorException in FileViewFinder.php line 137: View [default.views.errors.form_error] not found. (View: /home/vagrant/Code/acad/themes/Default/views/auth/login.blade.php)

**Comment by angelkurten** [comment]
It seems that is not the view, see if there is vistam and tell me if the problem continues

**Comment by ahmedelhadi** [comment]
```
[16:21:09] LOG.error: InvalidArgumentException: View [default.views.errors.form_error] not found. in...errorlog
```

**Comment by ahmedelhadi** [comment]
after fresh installation

**Comment by limaster** [comment]
I also have this problem @angelkurten

**Comment by limaster** [comment]
View [default.views.errors.form_error] not found

**Comment by limaster** [comment]
Is not that you did not submit view

**Comment by angelkurten** [comment]
The problem is generate because Linux / Ubuntu is case-sensitive, soon effected, the relevant changes

**Comment by angelkurten** [comment]
bug solved

**Comment by ahmedelhadi** [comment]
not solved

**Comment by dmitriy-01** [comment]
Changing `@include(view_path('errors.form-error'))` to `@include('errors.form-error')` in `Themes\Default\views\auth\login.blade.php` fixed this issue for me

**Comment by angelkurten** [comment]
@websquared Thanks

**Comment by Marian0** [comment]
Having the same issue

**Comment by ohluis** [comment]
I'm still getting the same error message.

**Comment by ohluis** [comment]
Has this project been abandoned? No recent updates?

**Comment by fahreza007** [comment]
@websquared Thank you man

**Comment by jramirezgranada** [comment]
@angelkurten you have to update views.php 
`'paths' => [
        realpath(base_path('Themes/Default/views')),
    ],` with this line the layout will work as you expect,
